-- 1.1 Users
CREATE TABLE users (
  user_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  email          VARCHAR2(255)   NOT NULL UNIQUE,
  password_hash  VARCHAR2(512)   NOT NULL,
  full_name      VARCHAR2(200),
  role           VARCHAR2(20)    NOT NULL
    CHECK (role IN ('USER','ADMIN'))
);

-- 1.2 Movies
CREATE TABLE movies (
  movie_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  title          VARCHAR2(500)   NOT NULL,
  release_year   NUMBER(4)       NOT NULL,
  description    CLOB,
  poster_url     VARCHAR2(1000),
  avg_rating     NUMBER(3,2)     DEFAULT 0
);

-- 1.3 Genres & Movie–Genre Link
CREATE TABLE genres (
  genre_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name           VARCHAR2(100)   NOT NULL UNIQUE
);

CREATE TABLE movie_genres (
  movie_id       NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  genre_id       NUMBER NOT NULL REFERENCES genres(genre_id) ON DELETE CASCADE,
  PRIMARY KEY (movie_id, genre_id)
);

-- 1.4 Actors & Movie–Cast Link
CREATE TABLE actors (
  actor_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name           VARCHAR2(200)   NOT NULL
);

CREATE TABLE movie_cast (
  movie_id       NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  actor_id       NUMBER NOT NULL REFERENCES actors(actor_id) ON DELETE CASCADE,
  character_name VARCHAR2(200),
  PRIMARY KEY (movie_id, actor_id)
);

-- 1.5 Ratings
CREATE TABLE ratings (
  rating_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id        NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  movie_id       NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  rating_value   NUMBER(2)       NOT NULL CHECK (rating_value BETWEEN 1 AND 10),
  created_at     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  UNIQUE (user_id, movie_id)
);

-- 1.6 Reviews
CREATE TABLE reviews (
  review_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id        NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  movie_id       NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  review_text    CLOB            NOT NULL,
  created_at     TIMESTAMP       DEFAULT SYSTIMESTAMP,
  updated_at     TIMESTAMP
);

-- 1.7 Watchlists
CREATE TABLE watchlists (
  watchlist_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id        NUMBER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  movie_id       NUMBER NOT NULL REFERENCES movies(movie_id) ON DELETE CASCADE,
  added_at       TIMESTAMP       DEFAULT SYSTIMESTAMP,
  UNIQUE (user_id, movie_id)
);